### ISSUE TITLE
embedder_inference.py crash

### ISSUE THREAD

**Issue by tianye2856** [vincent-thevenin/Realistic-Neural-Talking-Head-Models#14]
Hi, when I run the embedder_inference.py and it always crash on line 27
frame_mark_video = torch.from_numpy(np.array(frame_mark_video)).type(dtype = torch.float) #T,2,256,256,3

Traceback (most recent call last):
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/pydevd.py", line 1741, in <module>
    main()
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/pydevd.py", line 1735, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/pydevd.py", line 1135, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/danieltian/Desktop/Code/github_try/Realistic-Neural-Talking-Head-Models/embedder_inference.py", line 29, in <module>
    temp1 = torch.from_numpy(temp)
TypeError: can't convert np.ndarray of type numpy.object_. The only supported types are: float64, float32, float16, int64, int32, int16, int8, and uint8.

It seams that the value frame_mark_video returned from generate_cropped_landmarks is list of tuple, and it can not be converted to numpy array of float directly. Could you please fix this problem?
Thanks in advance.

**Comment by tianye2856** [comment]
Hi,
The problem is from the plot.figure, because the figure return size is 512x512x3, and the expected size is 256x256x3. So it seams very strange.

**Comment by vincent-thevenin** [comment]
Hi,
The error message you have is linked to modifications you made yourself on the code:
`temp1 = torch.from_numpy(temp)`

The following errors also look like they come from modifications you made on top of my code:
generate_cropped_landmarks does indeed return a list of tuple, and more specifically a list of tuple of numpy arrays of type uint8. Using np.array  on such a list should not be an issue, make sure you have the latest version of numpy or remove your modifications.
I can't find the plot.figure you're referencing, please post the line number but it looks like another modification since I crop any sizes back to 256x256x3 before making modifications.

Thanks for posting your issue but I can't fix them if they're not from this repo. Please open another issue if you find error in the master branch.
